article/urls.py
from django.urls import path
from .views import *

app_name='article'

urlpatterns = [
    path('',index,name='index'),
    path('article/search/',search_article,name='search'),
    path('article/<int:pk>/',single_article,name='single_article'),
    path('article/category/<int:pk>',categorised_article,name='categorised_article'),
    path('article/create/', create_article, name='create_article'), 
    path('article/update/<int:pk>/',UpdateArticle.as_view(),name="update_article"),
    path('article/delete/<int:pk>/',DeleteArticle.as_view(),name="delete_article"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("privacy/", privacy, name="privacy"),
    
    path('', include('article.urls')),
    path('users/',include('users.urls'))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %}

{% block content %} 

<div class="container" style="min-height:56.5vh;">
    <h1>
        This is an about  page!
    </h1>
</div>


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> {% endcomment %}

    <link rel="stylesheet" href="https://bootswatch.com/5/united/bootstrap.min.css"> 

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- JavaScript -->

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>


  <!-- JavaScript Popper -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  <!-- Bootstrap Max CDN --> 

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script> 

    <script src="https://kit.fontawesome.com/f16734b825.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static "style.css" %}">
</head>
<body>
    {% block nav %}
        <nav class="navbar navbar-expand-lg bg-body-tertiary shadow">
            <div class="container-fluid">
            <a class="navbar-brand" href="{% url "article:index" %}">GenZblogs</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url "article:index" %}"><i class="fa-solid fa-house"></i> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "article:create_article" %}"><i class="fa-solid fa-newspaper"></i> Post</a>  
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-list"></i> Categories
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                        <li><a class="dropdown-item" href="{% url "article:categorised_article" category.id  %}">{{category}}</a></li>
                        {% endfor %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url "article:categorised_article" 0 %}">All  </a></li>
                    </ul>
                </li>
                </ul>
                <form action="{% url "article:search" %}" class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
                <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <div class="auth d-flex mx-3">
                {% if user.is_authenticated %}
                <a class="nav-link text-decoration-none mx-3" href="{% url "profile" %}"><i class="fa-solid fa-user"></i> Profile</a>  
                <span class="">|</span> 
                <form class="nav-link" action="{% url "logout" %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-outline-danger py-0 border-0" type="submit"><i class="fa-solid fa-right-from-bracket"></i> Logout</button>
                </form>
                
                {% else %}
                <form class="nav-link" action="{% url "login" %}" method="POST">
                    {% csrf_token %}
                    <button class="tn btn-outline-dark py-0 border-0 mx-1" type="submit"><i class="fa-solid fa-right-to-bracket"></i> Login</button>
                </form>
                <span class="">|</span>
                <a class="nav-link text-decoration-none text-success mx-2" href="{% url "register" %}"><i class="fa-solid fa-user"></i> Register</a>  

                {% endif %}
            </div>
            </div>
            </div>
        </nav>
    {% endblock nav %}

    {% block content %}
    
    {% endblock content %}

    {% block footer %}
    <footer class="bg-black text-white mt-5">
        <div class="container py-4">
            <div class="row">
              <div class="col-md-4">
                <h4 class="text-success">About Us</h4>
                <p>This is a simple website for learning purposes.</p>
              </div>
              <div class="col-md-4">
                <h4 class="text-success">Quick Links</h4>
                <ul class="list-unstyled">
                  <li><a href="/about" class="text-white text-decoration-none">About</a></li> 
                  <li><a href="/contact" class="text-white text-decoration-none">Contact</a></li>
                  <li><a href="/privacy" class="text-white text-decoration-none">Privacy Policy</a></li>
                </ul>
              </div>
              <div class="col-md-4">
                <h4 class="text-success">Connect With Us</h4>
                <ul class="list-unstyled">
                  <li><a href="#" target="_blank" rel="noopener noreferrer" class="text-white text-decoration-none">Facebook</a></li>
                  <li><a href="#" target="_blank" rel="noopener noreferrer" class="text-white text-decoration-none">Twitter</a></li>
                  <li><a href="#" target="_blank" rel="noopener noreferrer" class="text-white text-decoration-none">Instagram</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="bg-secondary py-2">
            <div class="container">
              <div class="row">
                <div class="col-md-12 text-center">
                  <p class="mb-0">&copy; 2024 GenZblogs. All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
    </footer>
    {% endblock footer %}
</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="min-height:56.5vh;">
    <h1>
        This is a contact page!
        <a href="https://github.com/SrinithishB">Github</a>
    </h1>
</div>


{% endblock content %}

templates/privacy-policy.html
{% extends "base.html" %}

{% block content %}

<div class="container" style="min-height:56.5vh;">
    <h1>
        Our policy: DRY
    </h1>
</div> 

{% endblock content %}